### PR TITLE
Update CPP.pm

### PR DESCRIPTION
**Pull request by anthonybakermpls**
Add lines to remove lock file.

### CODE REVIEW

**Comment by anthonybakermpls** [comment]
Just added a line(s) to unlock or croak.

**Comment by anthonybakermpls** [comment]
Closing.

**Comment by daoswald** [comment]
No problem. Sorry I didn't have time last night to get to it.  Should come up with a resolution tonight though.

**Comment by anthonybakermpls** [comment]
I tried the method from slide 11 (http://perl.plover.com/yak/flock/samples/slide011.html) and it didn't help (so try that last if you are looking for new solutions). Our work-around is to completely remove the file locking code or chmod 777'ing the stale PERL_INLINE_DIRECTORY/.lock file seems to work too although that's probably really bad.

**Pull request closed without merging**
